### ISSUE TITLE
Authentication required

### ISSUE THREAD

**Issue by x3rxe5** [Quessts/EmailSpammer#1]
# This looks like sign in from non google app throws an error

#### ERROR: (535, b'5.7.8 Username and Password not accepted. Learn more at\n5.7.8  https://support.google.com/mail/?p=BadCredentials q73sm10626620pfc.179 - gsmtp');

Do we have to enable *** Less secure app access ??  ***

**Comment by Quessts** [comment]
Hey, I just tried it and looks like it's working perfectly. The issue must be on your end, please check your email (email you're sending from) you should've received an email requiring you to disable email security or something similar. I recommend using outlook to send emails instead since that doesn't require you to mess around with the outlook account a lot.

![Image](https://user-images.githubusercontent.com/54684166/137628205-d704f19e-896a-4fcb-8c2f-7658d2a04514.png)
